### ISSUE TITLE
Fail to start in macOS

### ISSUE THREAD

**Issue by wengkitttt** [AdguardTeam/AdGuardDNSClient#2]
### Prerequisites

- [X] I have checked the [Knowledge Base](https://adguard-dns.io/kb/) and the [Discussions](https://github.com/AdguardTeam/AdGuardDNSClient/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardDNSClient/discussions/categories/q-a)

- [X] I have set up AdGuard DNS Clients correctly and configured clients to use it. (Use the [Discussions](https://github.com/AdguardTeam/AdGuardDNSClient/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases

### Setup

On a personal machine

### AdGuard DNS Client version

v0.0.1

### Action

```sh
./AdGuardDNSClient -s start -v
```

### Expected result

The DNS Client should be started.

### Actual result

After run the start command, it show this error 

performing action "start": retrieving status: "launchctl" failed with stderr: Load failed: 5: Input/output error

**Comment by wengkitttt** [comment]
FYI, Im using M2 Mac Mini

**Comment by EugeneOne1** [comment]
@wengkitttt, hello and thanks for the report!  On macOS it's required for executables installed as services to be placed within `/Applications` directory.  What is the working directory in the issue?

**Comment by wengkitttt** [comment]
@EugeneOne1, I previously located the AdGuardDNSClient folder in the "Documents" directory. After moving it to the "Applications" folder and running sudo ./AdGuardDNSClient -s start -v, the status showed "running".

However, my DNS still didn't point to AdGuard DNS. I realized that I needed to change my DNS settings in `Settings -> Network -> Wifi -> Details` to point to 127.0.0.1 and ::1.

Now everything is working perfectly. Thanks for advising me to place the folder in "Applications".

**Comment by EugeneOne1** [comment]
@wengkitttt, hello again.  FYI, we've updated the [`README.md`](https://github.com/AdguardTeam/AdGuardDNSClient/blob/master/README.md#unix-like) and we will also publish the changes to the [knowledge base](https://adguard-dns.io/kb/dns-client/overview/#start-basic-unix) soon.
